/* Curated example sentences for Artho beta.
   Key: lowercase English word, or exact Assamese word.
   Value: array of [sentence, translation] pairs. Starter set — more coming. */
window.ARTHO_EXAMPLES = {
"good": [["She is a good teacher.", "তাই এগৰাকী ভাল শিক্ষয়িত্ৰী।"]],
"water": [["Drink more water every day.", "প্ৰতিদিনে বেছিকৈ পানী খোৱা।"]],
"book": [["This book is very interesting.", "এই কিতাপখন বৰ আমোদজনক।"]],
"love": [["They love their country.", "তেওঁলোকে নিজৰ দেশক ভাল পায়।"]],
"time": [["Time waits for no one.", "সময়ে কাৰো বাবে ৰৈ নাথাকে।"]],
"friend": [["He is my best friend.", "সি মোৰ আটাইতকৈ ভাল বন্ধু।"]],
"house": [["Our house is near the river.", "আমাৰ ঘৰ নৈৰ ওচৰত।"]],
"food": [["Assamese food is delicious.", "অসমীয়া খাদ্য বৰ সোৱাদ।"]],
"work": [["Hard work brings success.", "কঠোৰ পৰিশ্ৰমে সফলতা আনে।"]],
"school": [["The school opens at nine.", "বিদ্যালয় ন বজাত খোলে।"]],
"happy": [["The children look happy.", "ল'ৰা-ছোৱালীবোৰক সুখী দেখা গৈছে।"]],
"beautiful": [["The sunset is beautiful.", "সূৰ্যাস্তটো বৰ ধুনীয়া।"]],
"mother": [["My mother cooks well.", "মোৰ মাকে বৰ ভাল ৰান্ধে।"]],
"father": [["His father is a farmer.", "তেওঁৰ দেউতাক এজন খেতিয়ক।"]],
"child": [["The child is sleeping.", "শিশুটো শুই আছে।"]],
"dog": [["The dog barks at night.", "কুকুৰটোৱে ৰাতি ভুকে।"]],
"tree": [["Birds sit on the tree.", "চৰাইবোৰ গছত বহে।"]],
"river": [["The Brahmaputra is a big river.", "ব্ৰহ্মপুত্ৰ এখন ডাঙৰ নৈ।"]],
"sun": [["The sun rises in the east.", "সূৰ্য পূবত ওলায়।"]],
"moon": [["The moon shines at night.", "জোনে ৰাতি পোহৰ দিয়ে।"]],
"rain": [["Rain helps the crops grow.", "বৰষুণে শস্য গজাত সহায় কৰে।"]],
"dream": [["Follow your dreams.", "তোমাৰ সপোনবোৰ অনুসৰণ কৰা।"]],
"smile": [["Her smile is sweet.", "তাইৰ হাঁহিটো মৰমীয়া।"]],
"help": [["Please help the poor.", "দুখীয়াসকলক সহায় কৰা।"]],
"strong": [["He is strong and brave.", "সি শক্তিশালী আৰু সাহসী।"]],
"small": [["It is a small village.", "এইখন এখন সৰু গাঁও।"]],
"night": [["The stars shine at night.", "তৰাবোৰে ৰাতি জিলিকে।"]],
"day": [["Have a nice day!", "তোমাৰ দিনটো ভাল হওক!"]],
"market": [["We buy vegetables at the market.", "আমি বজাৰৰ পৰা শাক-পাচলি কিনো।"]],
"song": [["She sings a sweet song.", "তাই এটা মিঠা গান গায়।"]],
"ভাল": [["মই ভাল আছোঁ।", "I am fine."]],
"পানী": [["পানী জীৱন।", "Water is life."]],
"কিতাপ": [["মই কিতাপ পঢ়ি ভাল পাওঁ।", "I like reading books."]],
"মৰম": [["মাকে সন্তানক মৰম কৰে।", "A mother loves her child."]],
"সময়": [["সময়ৰ মূল্য বুজা।", "Understand the value of time."]],
"ঘৰ": [["ঘৰলৈ যাওঁ আহা।", "Come, let's go home."]],
"বন্ধু": [["বন্ধুৰ লগত ফুৰিবলৈ গ'লো।", "I went out with my friend."]],
"ৰাতি": [["ৰাতি সোনকালে শুবা।", "Sleep early at night."]],
"দিন": [["আজি বৰ ভাল দিন।", "Today is a very good day."]],
"সুখ": [["সুখ টকাৰে কিনিব নোৱাৰি।", "Happiness cannot be bought with money."]],
"দুখ": [["দুখৰ পাছত সুখ আহে।", "Happiness comes after sorrow."]],
"ডাঙৰ": [["এইটো এটা ডাঙৰ সপোন।", "This is a big dream."]],
"সৰু": [["সৰু ল'ৰাটোৱে খেলি আছে।", "The little boy is playing."]],
"ধুনীয়া": [["ফুলবোৰ বৰ ধুনীয়া।", "The flowers are very beautiful."]],
"মাক": [["মাকৰ মৰম অতুলনীয়।", "A mother's love is incomparable."]],
"গাঁও": [["মোৰ গাঁওখন বৰ শান্ত।", "My village is very peaceful."]],
"নৈ": [["নৈখন বৈ গৈ আছে।", "The river flows on."]],
"বৰষুণ": [["বৰষুণ দি আছে।", "It is raining."]],
"সপোন": [["সপোন দেখিবলৈ এৰি নিদিবা।", "Never stop dreaming."]],
"হাঁহি": [["তাইৰ হাঁহিটো ধুনীয়া।", "Her smile is beautiful."]]
};
